trouble with enum :(
org.postgresql.util.PSQLException: ERROR: column "actor" is of type chatactor but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 121